#!/usr/bin/env python3
"""Build and bundle the private ThirdReality v1.1.7 AEC3 runtime."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
from collections import deque
from pathlib import Path

_TOOLCHAIN_NAME = "gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu"
_TRIPLE = "aarch64-none-linux-gnu"
_APM_VERSION = "1.3"
_ABSEIL_VERSION = "20230802.1"
_DIST_SENTINEL = ".codex-aec3-dist"
_SYSTEM_LIBRARIES = frozenset(
    {
        "ld-linux-aarch64.so.1",
        "libasound.so.2",
        "libc.so.6",
        "libdl.so.2",
        "libgcc_s.so.1",
        "libm.so.6",
        "libpthread.so.0",
        "librt.so.1",
        "libstdc++.so.6",
    }
)
_NEEDED_PATTERN = re.compile(r"Shared library: \[([^]]+)]")
_VERSION_PATTERN = re.compile(r"Name: ((?:GLIBC|GLIBCXX|CXXABI)_[0-9.]+)")


def _parse_args() -> argparse.Namespace:
    module_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description=(
            "Cross-build against a populated ThirdReality v1.1.7 Buildroot "
            "staging tree and bundle only private APM/Abseil dependencies."
        )
    )
    parser.add_argument(
        "--toolchain-root",
        type=Path,
        required=True,
        help=f"path to the pinned {_TOOLCHAIN_NAME} directory",
    )
    parser.add_argument(
        "--buildroot-output",
        type=Path,
        required=True,
        help="Buildroot output directory containing staging/ and build/",
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=module_dir / "build-aarch64",
    )
    parser.add_argument(
        "--dist-dir",
        type=Path,
        default=module_dir / "dist-aarch64",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace a prior dist directory created by this script",
    )
    return parser.parse_args()


def _run(
    command: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return result.stdout


def _require_file(path: Path, description: str) -> Path:
    if not path.is_file():
        raise SystemExit(f"missing {description}: {path}")
    return path


def _validate_inputs(
    toolchain_root: Path,
    output: Path,
) -> tuple[Path, Path, Path, Path]:
    toolchain_root = toolchain_root.resolve()
    output = output.resolve()
    compiler = _require_file(
        toolchain_root / "bin" / f"{_TRIPLE}-g++",
        "pinned aarch64 compiler",
    )
    readelf = _require_file(
        toolchain_root / "bin" / f"{_TRIPLE}-readelf",
        "pinned aarch64 readelf",
    )
    staging = output / "staging"
    if not staging.is_dir():
        raise SystemExit(f"missing Buildroot staging directory: {staging}")
    _require_file(
        staging / "usr/lib/pkgconfig/webrtc-audio-processing-1.pc",
        "Buildroot WebRTC APM 1.x pkg-config metadata",
    )
    _require_file(
        staging / "usr/lib/pkgconfig/alsa.pc",
        "Buildroot ALSA pkg-config metadata",
    )
    version = _run([str(compiler), "--version"])
    if "10.2" not in version or _TRIPLE not in version:
        raise SystemExit(
            "compiler is not the v1.1.7 aarch64 GCC 10.2 toolchain:\n" + version
        )
    return toolchain_root, output, staging, readelf


def _prepare_dist(dist: Path, replace: bool) -> None:
    dist = dist.resolve()
    if dist.exists():
        if not replace:
            raise SystemExit(f"dist directory exists; pass --replace: {dist}")
        if not (dist / _DIST_SENTINEL).is_file():
            raise SystemExit(
                f"refusing to replace a directory without {_DIST_SENTINEL}: {dist}"
            )
        shutil.rmtree(dist)
    (dist / "bin").mkdir(parents=True)
    (dist / "lib").mkdir()
    (dist / "licenses").mkdir()
    (dist / _DIST_SENTINEL).write_text("generated by build_aarch64.py\n")


def _pkg_config_environment(staging: Path) -> dict[str, str]:
    env = dict(os.environ)
    env["PKG_CONFIG_SYSROOT_DIR"] = str(staging)
    env["PKG_CONFIG_LIBDIR"] = ":".join(
        (
            str(staging / "usr/lib/pkgconfig"),
            str(staging / "usr/share/pkgconfig"),
        )
    )
    return env


def _build(
    module_dir: Path,
    toolchain_root: Path,
    staging: Path,
    build_dir: Path,
    dist: Path,
) -> None:
    build_dir.mkdir(parents=True, exist_ok=True)
    env = _pkg_config_environment(staging)
    _run(
        [
            "cmake",
            "-S",
            str(module_dir),
            "-B",
            str(build_dir),
            "-G",
            "Ninja",
            "-DCMAKE_BUILD_TYPE=MinSizeRel",
            "-DCMAKE_TOOLCHAIN_FILE="
            + str(module_dir / "cmake/thirdreality-aarch64.cmake"),
            f"-DTHIRDREALITY_TOOLCHAIN_ROOT={toolchain_root}",
            f"-DTHIRDREALITY_STAGING_DIR={staging}",
            f"-DCMAKE_INSTALL_PREFIX={dist}",
        ],
        env=env,
    )
    _run(["cmake", "--build", str(build_dir), "--parallel"], env=env)
    _run(["cmake", "--install", str(build_dir), "--strip"], env=env)


def _needed(readelf: Path, binary: Path) -> list[str]:
    output = _run([str(readelf), "--dynamic", str(binary)])
    return _NEEDED_PATTERN.findall(output)


def _library_index(staging: Path) -> dict[str, Path]:
    index: dict[str, Path] = {}
    for directory in (staging / "lib", staging / "usr/lib"):
        if not directory.is_dir():
            continue
        for candidate in directory.glob("*.so*"):
            index.setdefault(candidate.name, candidate)
    return index


def _bundle_private_libraries(readelf: Path, staging: Path, dist: Path) -> None:
    index = _library_index(staging)
    pending = deque((dist / "bin").glob("*"))
    pending.extend((dist / "lib").glob("*.so*"))
    inspected: set[Path] = set()
    while pending:
        binary = pending.popleft()
        if binary in inspected or not binary.is_file():
            continue
        inspected.add(binary)
        for name in _needed(readelf, binary):
            if name in _SYSTEM_LIBRARIES:
                continue
            destination = dist / "lib" / name
            if destination.is_file():
                pending.append(destination)
                continue
            source = index.get(name)
            if source is None:
                raise SystemExit(
                    f"could not resolve private runtime dependency {name} "
                    f"needed by {binary}"
                )
            shutil.copy2(source.resolve(), destination)
            pending.append(destination)


def _version_tuple(value: str) -> tuple[int, ...]:
    return tuple(int(part) for part in value.split("_", 1)[1].split("."))


def _audit_abi(readelf: Path, dist: Path) -> dict[str, list[str]]:
    requirements: dict[str, list[str]] = {}
    limits = {
        "GLIBC": (2, 31),
        "GLIBCXX": (3, 4, 28),
        "CXXABI": (1, 3, 12),
    }
    artifacts = sorted((dist / "bin").glob("*")) + sorted(
        (dist / "lib").glob("*.so*")
    )
    for artifact in artifacts:
        header = _run([str(readelf), "--file-header", str(artifact)])
        if "Machine:" not in header or "AArch64" not in header:
            raise SystemExit(f"artifact is not AArch64 ELF: {artifact}")
        version_output = _run([str(readelf), "--version-info", str(artifact)])
        names = sorted(set(_VERSION_PATTERN.findall(version_output)))
        requirements[str(artifact.relative_to(dist))] = names
        for name in names:
            family = name.split("_", 1)[0]
            if family in limits and _version_tuple(name) > limits[family]:
                raise SystemExit(
                    f"{artifact} requires {name}, exceeding v1.1.7 "
                    f"{family}_{'.'.join(map(str, limits[family]))}"
                )
    return requirements


def _copy_licenses(module_dir: Path, output: Path, dist: Path) -> None:
    build = output / "build"
    sources = {
        "webrtc-audio-processing-BSD-3-Clause.txt":
            build / f"webrtc-audio-processing-{_APM_VERSION}/COPYING",
        "libabseil-cpp-Apache-2.0.txt":
            build / f"libabseil-cpp-{_ABSEIL_VERSION}/LICENSE",
    }
    for destination, source in sources.items():
        _require_file(source, f"license for {destination}")
        shutil.copy2(source, dist / "licenses" / destination)
    shutil.copy2(
        module_dir / "THIRD_PARTY_NOTICES.md",
        dist / "THIRD_PARTY_NOTICES.md",
    )


def _copy_runtime_files(module_dir: Path, dist: Path) -> None:
    for name in ("__init__.py", "recorder.py", "README.md"):
        shutil.copy2(module_dir / name, dist / name)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(128 * 1_024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_manifest(
    dist: Path,
    abi_requirements: dict[str, list[str]],
) -> None:
    files = {
        str(path.relative_to(dist)): _sha256(path)
        for path in sorted(dist.rglob("*"))
        if path.is_file() and path.name not in {_DIST_SENTINEL, "manifest.json"}
    }
    manifest = {
        "schema": 1,
        "target": "thirdreality-v1.1.7-aarch64",
        "toolchain": _TOOLCHAIN_NAME,
        "webrtc_audio_processing": _APM_VERSION,
        "libabseil_cpp": _ABSEIL_VERSION,
        "capture": {
            "device": "hw:0,4",
            "format": "S16_LE",
            "sample_rate": 16_000,
            "channels": 4,
            "mic_channel": 0,
            "reference_channels": [2, 3],
            "period_frames": 160,
            "stream_delay_ms": 0,
        },
        "files": files,
        "abi_requirements": abi_requirements,
    }
    (dist / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )


def _write_archive(dist: Path, replace: bool) -> Path:
    archive = dist.with_suffix(".tar.gz")
    if archive.exists() and not replace:
        raise SystemExit(f"archive exists; pass --replace: {archive}")
    with (
        archive.open("wb") as raw,
        gzip.GzipFile(fileobj=raw, mode="wb", mtime=0) as compressed,
        tarfile.open(fileobj=compressed, mode="w") as output,
    ):
        for path in sorted(dist.rglob("*")):
            if path.name == _DIST_SENTINEL:
                continue
            info = output.gettarinfo(
                str(path),
                arcname=str(Path("aec3_capture") / path.relative_to(dist)),
            )
            info.uid = 0
            info.gid = 0
            info.uname = "root"
            info.gname = "root"
            info.mtime = 0
            if path.is_file():
                with path.open("rb") as source:
                    output.addfile(info, source)
            else:
                output.addfile(info)
    return archive


def main() -> int:
    """Build, audit, license, and deterministically archive the runtime."""

    args = _parse_args()
    module_dir = Path(__file__).resolve().parent
    toolchain, output, staging, readelf = _validate_inputs(
        args.toolchain_root, args.buildroot_output
    )
    dist = args.dist_dir.resolve()
    _prepare_dist(dist, args.replace)
    _build(
        module_dir,
        toolchain,
        staging,
        args.build_dir.resolve(),
        dist,
    )
    _bundle_private_libraries(readelf, staging, dist)
    abi_requirements = _audit_abi(readelf, dist)
    _copy_licenses(module_dir, output, dist)
    _copy_runtime_files(module_dir, dist)
    _write_manifest(dist, abi_requirements)
    archive = _write_archive(dist, args.replace)
    sys.stdout.write(f"{archive}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
